[huggingface]
huggingface_api_key = "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"

[gemini]
gemini_api_key = "AIzaSyBwMy8f0xj4D1hLpFvPSnT3L0_gpYTJlVY"

[langchain]
langsmith_api_key = "ls__9564d3e253174c5886d137c43d444cab"